package dk.via.sep.shared.utils;

public enum UserAction {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    LOGIN_SUCCESS_ADMIN,
    USER_LIST,
    PROFILE_EDIT,
    EVENT_REMOVE,
    EVENT_CREATE,
    EVENT_CREATE_SUCCESS,
    EVENT_CREATE_FAILED,
    EVENT_EDIT,
    EVENT_JOIN,
    EVENT_JOIN_SUCCESS,
    EVENT_JOIN_FAILED,
    EVENT_LEAVE_SUCCESS,
    EVENT_LEAVE_FAILED,
    EVENT_LIST
}
