package dk.via.sep.shared.utils;

public enum UserAction {
    LOGIN,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    REGISTER,
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    LOGIN_SUCCESS_ADMIN,
    USER_LIST,
    EVENT_REMOVE,
    EVENT_CREATE,
    EVENT_CREATE_SUCCESS,
    EVENT_CREATE_FAILED,
    EVENT_EDIT
}
